// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWA-_2A2C0DysGaFSpc_Osv77Bi1mTS3M',
    appId: '1:475313564724:web:c80dcbc6327f41919bae61',
    messagingSenderId: '475313564724',
    projectId: 'neoaiapp-e0686',
    authDomain: 'neoaiapp-e0686.firebaseapp.com',
    storageBucket: 'neoaiapp-e0686.appspot.com',
    measurementId: 'G-FYSV0E0NEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExSyS_7W_-BWKKyTuyC_Q59Ifnpl9oj0',
    appId: '1:475313564724:android:d3c09bf53e359dfb9bae61',
    messagingSenderId: '475313564724',
    projectId: 'neoaiapp-e0686',
    storageBucket: 'neoaiapp-e0686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQNZbYSdPU_ToOURAtGFqcRIhFjVyhKA',
    appId: '1:475313564724:ios:b3896f85c2edf46b9bae61',
    messagingSenderId: '475313564724',
    projectId: 'neoaiapp-e0686',
    storageBucket: 'neoaiapp-e0686.appspot.com',
    androidClientId: '475313564724-c2d788rl7j5puo4gcbmjk9is9d0a2ojt.apps.googleusercontent.com',
    iosClientId: '475313564724-ki6vuh9p249dmtvmo6trlcnbe1chfuhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.neoAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXQNZbYSdPU_ToOURAtGFqcRIhFjVyhKA',
    appId: '1:475313564724:ios:6a5d4e7979a404b89bae61',
    messagingSenderId: '475313564724',
    projectId: 'neoaiapp-e0686',
    storageBucket: 'neoaiapp-e0686.appspot.com',
    androidClientId: '475313564724-c2d788rl7j5puo4gcbmjk9is9d0a2ojt.apps.googleusercontent.com',
    iosClientId: '475313564724-alq324so696to5m047ap60vjaj0fba3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.neoAiApp.RunnerTests',
  );
}
